config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'

  resources :posts do
  resources :comments, only: :create
  resources :photos, only: :create
  end

  resources :posts
  resources :groups do
    resources :posts
    member do
      patch 'join'
      patch 'leave'
    end
  end
  resources :friends, only: %i[index create destroy] do
    collection do
      get 'search'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/friend.rb
# frozen_string_literal: true

class Friend < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :posts
  mount_uploader :group_avatar, GroupAvatarUploader
  mount_uploader :group_banner, GroupBannerUploader
  belongs_to :owner, class_name: 'User', optional: false, validate: true

  validates :name, presence: true
  validates :description, presence: true
  validates :group_banner, presence: :true
  validates :group_avatar, presence: :true
  validates :category, presence: :true
end

app/models/photo.rb
class Photo < ApplicationRecord

  mount_uploader :picture
  belongs_to :user
  belongs_to :post

end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  #mount_uploader :avatar, AvatarUploader
  belongs_to :group, optional: true
  has_many :comments
  validates :text, presence: true, length: { minimum: 2 }

  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :friends
  has_and_belongs_to_many :groups
  #has_one_attached :avatar

  scope :with_name_or_email, lambda { |q|
                               where '(name ILIKE ?) OR (email ILIKE ?)',
                                     "%#{q}%", "%#{q}%"
                             }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :birth_date, :avatar, :avatar_cache) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :birth_date, :avatar, :avatar_cache) }
    end
end
# frozen_string_literal: true

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params.merge(user: current_user))
    redirect_to post_path(@post)
   end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/friends_controller.rb
# frozen_string_literal: true

class FriendsController < ApplicationController
  def index
    # @friends = Friend.includes(:user).where(user: current_user).order('Users.name')
    @friends = current_user.friends.includes(:user).order('Users.name')
  end

  # /friends/search?q=john
  def search
    q = params[:q]
    @possible_friends = User.with_name_or_email(q).order(:name)
  end

  def create
    # @post = current_user.posts.create(post_params)
  end

  def destroy
    # @post = Post.find(params[:id])
  end

  private

  def user_params
    params.require(:friend).permit(:friend_id)
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true
class GroupsController < ApplicationController
  before_action :authenticate_user!


  def index
    @groups = Group.all.order(:name)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner = current_user
    @group.users << current_user
    @group.save
    redirect_to group_path(@group)
  end

  def destroy
    if current_user == current_group.owner
      current_group.destroy
      redirect_to root_path
    else
      redirect_to group_path(current_group), alert: 'You are not the owner of the group.'
    end
  end

  def edit; end

  def update; end

  def join
    if current_group.users.include? current_user
      redirect_to group_path(current_group), alert: "You are already a member"
    else
      current_group.users << current_user
      redirect_to group_path(current_group)
    end
  end

  def leave
    if current_user == current_group.owner
      redirect_to group_path(current_group),alert: "Group owners cannot leave groups, pass ownership or delete group."
    else
      current_group.users.delete(current_user)
      redirect_to group_path(current_group) 
    end
      
  end

  def show

  end

  private

  helper_method :current_group
  def current_group
    @current_group ||= Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :description, :category, :group_avatar, :group_banner)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

 def create
    @post = Post.find(params[:post_id])
     @post.photos.create(photo_params.merge(user: current_user))
      redirect_to post_path(@post)


  end

private

  def photo_params
    params.require(:photo).permit(:picture, :text)
  end

end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
    def index
      search = params[:search]

      if search.present?
        puts "present"
        name = search[:search]
        @posts = Post.joins(:user).where('users.name ILIKE ?', "%#{name}%")
      else
        @posts = Post.all

      end
    end

  def new
    @post = Post.new
  end

  def create
    if current_user.posts.create(post_params).valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @post = Post.find(params[:id])

    if @post.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end

    @post.update_attributes(post_params)
    if @post.valid?
      redirect_to root_path

    else
      render :edit, status: :unprocessable_entity
  
    end
  end

  private

  def post_params
    params.require(:post).permit(:text, :photo, :video)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def new; end

  def create; end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

module GroupsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def user_avatar(user, size=40)
    if user.avatar.attached?
      user.avatar.variant(resize: "#{size}x#{size}!")
    else
      user.png(user.email, size: size)
    end
  end
end

app/views/friends/index.html.erb
<h3>Friends</h3>

<% if @friends.count > 0 %>
<div>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th width="35%">Email</th>
        <th width="35%">Name</th>
     </tr>
    </thead>

    <tbody>
      <% @friends.each do |f| %>
        <tr>
          <td width="35%"><%= f.friend.email %></td>
          <td width="35%"><%= f.friend.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<% else %>

<p>No friends found.</p>

<% end %>

app/views/groups/index.html.erb
<br />
  <% if @groups.present? %>
    <% @groups.each do |group| %>
    <div class="row">
      <div class="booyah-box col-10 offset-1">
        <h2 class="text-center">
          <%= link_to group.name, group_path(group) %>
        </h2>
        <%= link_to group_path(group) do %>
          <%= image_tag group.group_avatar.url class: 'img-fluid' %>
        <% end %>
        <h2 align="middle"> <%= group.description %> </h2>
      </div>
    </div>
    <% end %>
  <% end %>

app/views/groups/new.html.erb
<h1> Add a new group thingy here and stuff </h1>

<%= simple_form_for @group, url: groups_path do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :category %>
  <%= f.input :group_banner, hint: 'Recommended size is 468x60, it will be resized.' %>
  <%= f.input :group_avatar, hint: 'Recommended size is 180x180, it will be resized.'%>
  <br />
  <%= f.submit "Create Group", class: 'btn btn-primary' %>
  <br />
<% end %>

app/views/groups/show.html.erb
<div class="booyah-box col-10 offset-1">
  <div class="banner">
    <%= image_tag current_group.group_banner.url class: 'img-fluid' %>
  </div>

  <h1 align="left"> <%= current_group.name %></h1>


  <br />
  <h2><%= current_group.description %></h2>

  <% if !current_group.users.include? current_user %>

    <%= link_to 'Join Group',join_group_path(current_group), method: :patch, class: 'btn btn-primary' %>

  <% elsif (current_group.users.include? current_user) && !(current_user == current_group.owner) %>

    <%= link_to 'Leave Group', leave_group_path(current_group), method: :patch, class: 'btn btn-primary' %>

  <% else current_user == current_group.owner %>
    <%= link_to 'Delete group', group_path(current_group), method: :delete, class: 'btn btn-primary' %>

  <% end %>

</div>

app/views/posts/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Post</h1>
  <%= simple_form_for @post do |f| %>
    <%= f.input :text %>
    <%= f.input :photo %>
    <%= f.input :video %>
    <br />
    <%= f.submit 'Update', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', root_path, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<h1>Your Posts</h1>

 <%= simple_form_for :search, url: posts_path, method: "GET", html: { class: 'form-inline' } do |f| %>
   <%= f.input :search, label: '', placeholder: 'Search' %>
   <%= f.submit 'Search', class: 'btn btn-primary' %>
   <% end %>

<% @posts.each do |post| %>
<div>
  <div class="booyah-box col-10 offset-1">
  <h1><%= link_to post.text, posts_path(post) %></h1><br />
  <p><%= post.photo %></p><br />
  <p><%= post.video %></p><br />

    
    <% if post.comments.present? %>
  <div class="col-12">
    <blockquote>
       <%= post.comments.last.text %>
      <small><%= post.comments.last.user.name %></small>
    </blockquote>
  </div>
  <% end %>

<% end %>
</div>

<% end %>

 

app/views/posts/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>New Post</h1>
  <%= simple_form_for @post do |f| %>
    <%= f.input :text %>
    <%= f.label :photo %>
    <%= f.file_field :photo%>
    <%= f.label :video %>
    <%= f.file_field :video %>
    <br />
    <%= f.submit 'Post', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', root_path, class: "btn btn-secondary" %>
    <% end %>
</div>


app/views/posts/show.html.erb
</br>
</br>
<div class="booyah-box col-10 offset-1">
  <h4><%= @post.text %></h4>
  <br />
  <p><%= @post.photo %></p>
  <br />
  <p><%= @post.video %></p>
  
  <div class="float-right">
    <% if current_user && current_user == @post.user %>
      <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary'%>
    <% end %>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
        <%= simple_form_for @comment, url: post_comments_path(@post) do |f| %>
          <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
            <div class="modal-body">
              <%= f.input :text %>
              <%= f.input :photo %>
              <%= f.input :video %>
            <br />
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
            </div>
          <% end %>
    </div>
  </div>
</div>

<div class= "clear"></div>

<br>
<br>

<div class="col-8 offset-1">
  <h1 class="float-left">Photos</h1>
</div>

 <!-- Button trigger modal picture -->
<button type="button" class="btn btn-primary btn-lg float-right" data-toggle="modal" data-target="#photoModal">
  Add a photo
</button>

<!-- Modal -->

<div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add A Photo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for @photo, url: post_photos_path(@post) do |f| %>
        <%= f.input :text %>
        <%= f.input :picture %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add Photo", class: 'btn btn-primary' %>
      </div>
        <% end %>
    </div>
  </div>
</div>


</div>
  
<div>
  <% @post.photos.each do |photo| %>
  <div>
    <% if photo.picture.url %>
    <%= image_tag photo.picture.url, class: 'show-image-size' %>
    <%= photo.caption %>
    <% end %>
  </div>
  <div>
   <%= photo.caption %>
  </div>
  <% end %>
</div>

app/views/static_pages/index.html.erb
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">

<div class="clear"></div>

<br /><br />
<% @posts.each do |post| %>

  <% if post.user.present? %>
    <div class="booyah-box col-10 offset-1">
      <h1><%= link_to post.text, post_path(post) %></h1><br />
      <p><%= post.photo %></p>
      <p><%= post.video %></p>
      <%= post.created_at.strftime("%B %d %Y, %l:%M%P") %>
      <div>
        <% if post.user.avatar? %>
          <%= image_tag post.user.avatar.url, class:'avatar_image'%>
        <% else %>
          <%= image_tag "user.png", class:'avatar_image' %>
        <% end %>
      </div>
      <h3><%= post.user.name %></h3>
      <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
          Add a comment
        </button>
    </div>
  <% end %>

  
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
      <br />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>

  </div>
</li> 
</ul>
</div>              
</div>
  
  <% if post.comments.present? %>
    <div class="col-12">
      <blockquote>
        <%= post.comments.last.text %>
        <small><%= post.comments.last.user.name %></small>
          <div>
            <% if post.comments.user.avatar? %>
              <%= image_tag post.user.avatar.url, class:'avatar_image'%>
            <% else %>
              <%= image_tag "user.png", class:'avatar_image' %>
            <% end %>
          </div>
      </blockquote>
    </div>
  <% end %>
<% end %>
</div>
     

<%= link_to 'Create a group', new_group_path, class: 'btn btn-primary' %>
<%= link_to 'View Groups', groups_path, class: 'btn btn-primary' %>

app/views/users/show.html.erb
<h1>Profile for <%= @user %></h1>